Q1:Read about the movielens dataset and write down a summary of metadata.

The given dataset describes 5-star rating and free-text tagging activity from [MovieLens](http://movielens.org), a movie recommendation service. 
*   No. of ratings: 100836
*   No. of tags: 3683
*   No. of movies: 9742
*   No. of users: 610
*   Timeframe of data collection: 29/03/96 - 24/09/18
*   Dataset genration date: 26/09/2018
* Users were selected at random for inclusion. All selected users had rated at least 20 movies. No demographic information is included. Each user is represented by an id, and no other information is provided.Datasets involved:
*   links.csv
*   movies.csv
*   ratings.csv
*   tags.csv
*  Attributes present:
*   User id - All users have unique id
*   Movie Ids - It is an identifier for movies used by https://movielens.org. Only movies with at least one rating or tag are included in the dataset. 
*   rating - Ratings are made on a 5-star scale, with half-star increments (0.5 stars - 5.0 stars)
*   Timestamp -Seconds passed since midnight of January 1, 1970.
*   Tags - user-generated metadata about movies; typically a single word or short phrase.

In [64]:
#Importing all the necessary libraries
import pandas as pd
import numpy as np
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [65]:
#Importing the required datasets
ratings = pd.read_csv("/content/sample_data/ratings.csv")
movies = pd.read_csv("/content/sample_data/movies.csv")
tags = pd.read_csv("/content/sample_data/tags.csv")
links = pd.read_csv("/content/sample_data/links.csv")

In [80]:
#Merging the datasets 'ratings' and 'movies' with the attribute 'movieId'
df=pd.merge(ratings,movies,on="movieId",how="left",sort="False")
df.head()

   userId  ...                                       genres
0       1  ...  Adventure|Animation|Children|Comedy|Fantasy
1       5  ...  Adventure|Animation|Children|Comedy|Fantasy
2       7  ...  Adventure|Animation|Children|Comedy|Fantasy
3      15  ...  Adventure|Animation|Children|Comedy|Fantasy
4      17  ...  Adventure|Animation|Children|Comedy|Fantasy

[5 rows x 6 columns]

User-Based Similarity

Q2:Read the “ratings.csv” file and create a pivot table with index=‘userId’, columns=‘movieId’,
values = “rating.

In [67]:
#Creating a pivot table
table = pd.pivot_table(df, values ='rating', index ='userId',columns =['movieId'],fill_value=0)
table.head()

movieId  1       2       3       4       ...  193583  193585  193587  193609
userId                                   ...
1           4.0     0.0     4.0     0.0  ...     0.0     0.0     0.0       0
2           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0       0
3           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0       0
4           0.0     0.0     0.0     0.0  ...     0.0     0.0     0.0       0
5           4.0     0.0     0.0     0.0  ...     0.0     0.0     0.0       0

[5 rows x 9724 columns]

Q3:sklearn.metrics.pairwise_distances can be used to compute distance between all pairs of
users. pairwise_distances() takes a metric parameter for what distance measure to use. Use
cosine similarity for finding similarity among users. Use the following packages.

Q4:from sklearn.metrics import pairwise_distances

Q5:from scipy.spatial.distance import cosine, correlation

In [68]:
#using pairwise_distances from sklearn for calculating distance between instances in a feature array
pairwise_dist = pairwise_distances(table,metric="cosine") #array is created
pairwise_dist_table= pd.DataFrame(np.squeeze(pairwise_dist))  #using squeeze function from numpy to remove single-dimensional entries from the shape of an array
pairwise_dist_table

              0             1             2    ...       607           608       609
0    1.110223e-16  9.727171e-01  9.402797e-01  ...  0.708903  9.064281e-01  0.854679
1    9.727171e-01  1.110223e-16  1.000000e+00  ...  0.953789  9.724346e-01  0.897573
2    9.402797e-01  1.000000e+00  1.110223e-16  ...  0.978872  1.000000e+00  0.967881
3    8.056052e-01  9.962741e-01  9.977486e-01  ...  0.850142  9.678020e-01  0.892317
4    8.709201e-01  9.833856e-01  9.949803e-01  ...  0.864465  7.387679e-01  0.939208
..            ...           ...           ...  ...       ...           ...       ...
605  8.358085e-01  9.715710e-01  9.870070e-01  ...  0.737442  9.303783e-01  0.798896
606  7.306108e-01  9.870521e-01  9.807532e-01  ...  0.716919  8.508097e-01  0.860886
607  7.089026e-01  9.537890e-01  9.788715e-01  ...  0.000000  8.780073e-01  0.677945
608  9.064281e-01  9.724346e-01  1.000000e+00  ...  0.878007  2.220446e-16  0.946775
609  8.546792e-01  8.975732e-01  9.678813e-01  ...  0.677945  9.467745e-01  0.000000

[610 rows x 610 columns]

Q6:Find the 5 most similar user for user with user Id 10.

In [69]:
#storing the userId = 10 in a variable
user_10_id=df['userId']==10
df[user_10_id]

       userId  ...                                       genres
7865       10  ...                  Comedy|Crime|Drama|Thriller
10023      10  ...                     Comedy|Drama|Romance|War
15472      10  ...  Adventure|Animation|Children|Comedy|Musical
16793      10  ...                               Comedy|Romance
20584      10  ...                                Drama|Romance
...       ...  ...                                          ...
97978      10  ...                Action|Adventure|Comedy|Crime
98623      10  ...                                 Comedy|Drama
99053      10  ...                       Action|Adventure|Crime
99142      10  ...                                 Comedy|Drama
99259      10  ...                                       Comedy

[140 rows x 6 columns]

In [70]:
#Calculating cosine similiarity for userId = 10
every_user=table.values
user_10_id_=every_user[0]
denominator1=np.sqrt(sum([np.square(x) for x in user_10_id]))
cosine_similiarity=[(10,1)]
i=1
for user in every_user[1:]:
    numerator=[x*y for x,y in zip(user_10_id,user)]
    denominator2=np.sqrt(sum([np.square(x) for x in user]))
    costheta = sum(numerator)/(denominator1*denominator2)
    cosine_similiarity.append((table.index[i],costheta))
    i=i+1
cosine_similiarity.sort(key=lambda x:x[1],reverse =True)
similiar_10_users=cosine_similiarity[0:6]
similiar_10_users

[(10, 1),
 (24, 0.008736727950735655),
 (246, 0.005478501187115793),
 (222, 0.004901561654854979),
 (21, 0.004708375682594021),
 (292, 0.004087059080284815)]

In [71]:
#mapping the previous results for top 5 similiar users into a table
top_5_users_df = pd.DataFrame()
top_5_users_df
for user in similiar_10_users:
  top_5_users_df = top_5_users_df.append(table.loc[user[0]])
top_5_users_df['costheta'] = [user[1] for user in similiar_10_users]
total_values = top_5_users_df.values
top_5_users_df

       1    2    3    4    5  ...  193583  193585  193587  193609  costheta
10   0.0  0.0  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  1.000000
24   0.0  0.0  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  0.008737
246  0.0  0.0  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  0.005479
222  0.0  2.5  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  0.004902
21   3.5  3.5  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  0.004708
292  4.0  0.0  0.0  0.0  0.0  ...     0.0     0.0     0.0     0.0  0.004087

[6 rows x 9725 columns]

Q7: Use the “movies” dataset to find out the names of movies, user 2 and user 338 have
watched in common and how they have rated each one of them.

In [72]:
#Creation of the sets
ui2 = set(df[df['userId']==2].movieId)
ui338 = set(df[df['userId']==338].movieId)

In [73]:
#Intersection of the sets
uint = ui2.intersection(ui338)
uint

{318, 6874}

In [112]:
#to find the common movies between user2 and user338
movies[(movies.movieId==318) | (movies.movieId==6874)]

      movieId                             title                 genres
277       318  Shawshank Redemption, The (1994)            Crime|Drama
4615     6874          Kill Bill: Vol. 1 (2003)  Action|Crime|Thriller

Inference: Movies common to user2 and user338 are: Shawshank Redemption, The (1994) and Kill Bill: Vol. 1 (2003)

In [113]:
user_ratings = ratings[(ratings.movieId==318) | (ratings.movieId==6874)]
#display user2 rating  
user2_ratings=user_ratings[user_ratings.userId==2]
display(user2_ratings)
#display user338 rating  
user338_ratings=user_ratings[user_ratings.userId==338]
display(user338_ratings)

     userId  movieId  rating   timestamp
232       2      318     3.0  1445714835
236       2     6874     4.0  1445714952

       userId  movieId  rating   timestamp
51972     338      318     5.0  1530148309
51982     338     6874     4.5  1530148453


 Ratings given by user2 :
* Shawshank Redemption, The (1994) is: 3.0 
* Kill Bill: Vol. 1 is:4.0

Ratings given by user338 :
* Shawshank Redemption, The (1994) is: 5.0 
* Kill Bill: Vol. 1 is:4.5

Q8:Use the movies dataset to find out the common movie names between user 2 and user 338
with least rating of 4.0

In [115]:
user_ratings = ratings[(ratings.movieId==318) | (ratings.movieId==6874)]
#display user2 rating  
user2_ratings=user_ratings[user_ratings.userId==2]
display(user2_ratings)
#display user338 rating  
user338_ratings=user_ratings[user_ratings.userId==338]
display(user338_ratings)

     userId  movieId  rating   timestamp
232       2      318     3.0  1445714835
236       2     6874     4.0  1445714952

       userId  movieId  rating   timestamp
51972     338      318     5.0  1530148309
51982     338     6874     4.5  1530148453

Inference: Clearly the common movie between user 2 and user 338
with least rating of 4.0 is Kill Bill: Vol. 1 (2003)

Item-Based Similarity

Q9: Create a pivot table for representing the similarity among movies using correlation.

In [101]:
table2 = pd.pivot_table(df,values='rating',columns='title',index='userId').fillna(0)
table2.head()

title   '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
userId              ...
1              0.0  ...                                        0.0
2              0.0  ...                                        0.0
3              0.0  ...                                        0.0
4              0.0  ...                                        0.0
5              0.0  ...                                        0.0

[5 rows x 9719 columns]

In [100]:
#creation of pivot table
item_similiarity = table2.corr(method = 'pearson')
item_similiarity

title                                      '71 (2014)  ...  À nous la liberté (Freedom for Us) (1931)
title                                                  ...
'71 (2014)                                   1.000000  ...                                  -0.001642
'Hellboy': The Seeds of Creation (2004)     -0.001642  ...                                  -0.001642
'Round Midnight (1986)                      -0.002324  ...                                  -0.002324
'Salem's Lot (2004)                         -0.001642  ...                                  -0.001642
'Til There Was You (1997)                   -0.002254  ...                                  -0.002254
...                                               ...  ...                                        ...
eXistenZ (1999)                             -0.007675  ...                                  -0.007675
xXx (2002)                                   0.134327  ...                                  -0.007744
xXx: State of the Union (2005)               0.325287  ...                                  -0.003594
¡Three Amigos! (1986)                       -0.008185  ...                                  -0.008185
À nous la liberté (Freedom for Us) (1931)   -0.001642  ...                                   1.000000

[9719 rows x 9719 columns]

Q10:Find the top 5 movies which are similar to the movie “Godfather”.

In [52]:

display(table2.corr()['Godfather, The (1972)'].sort_values(ascending=False).iloc[:6])

title
Godfather, The (1972)                     1.000000
Godfather: Part II, The (1974)            0.769390
Goodfellas (1990)                         0.560246
One Flew Over the Cuckoo's Nest (1975)    0.496048
Reservoir Dogs (1992)                     0.442128
Fargo (1996)                              0.418042
Name: Godfather, The (1972), dtype: float64